version: '3.9'

services:
  database:
    image: postgres:12
    container_name: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5431:5431"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
  redis:
    image: 'redis:7-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'
  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
      - redis
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    env_file: .env
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres@database
      REDIS_URL: redis://redis:6379/1
  sidekiq:
    depends_on:
      - database
      - redis
    image: 'trucking_web:latest'
    command: bundle exec sidekiq -C config/sidekiq.yml
    volumes:
      - '.:/app'
    environment:
      REDIS_URL: redis://redis:6379/1
volumes:
  redis:
  gem_cache:
  db_data:
  node_modules:
