development:
  :concurrency: 1

production:
  :concurrency: 1

:max_retries: 1

:queues:
  - mailers
  - default

:schedule:
  user_birthday:
    cron: '0 * 9-10 * * 1-5'   # Runs from Monday to Friday every day at 9 - 10 a.m.
    class: UsersBirthdayJob
